### Default variable file for taxonomy-service ###

api_namespace: knowlg-api

env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: docker.io/aimansharief/taxonomy-service
image_tag: R5.2.0
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 9006
  targetport: 9000
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%
serviceType: ClusterIP 
cassandra_connection: cassandra-db.knowlg-db.svc.cluster.local:9043
redis_connection: redis-db.knowlg-db.svc.cluster.local
kafka_connection: kafka.knowlg-db.svc.cluster.local:9092
objectcategorydefinition_keyspace: dev_category_store

# JanusGraph with Yugabyte CQL Backend
janusgraph_storage_backend: cql
janusgraph_storage_hostname: sunbird-yugabyte-tserver.knowlg-db.svc.cluster.local
janusgraph_storage_port: 9042
janusgraph_storage_keyspace: janusgraph
janusgraph_storage_replication_factor: 3
janusgraph_storage_consistency_level: QUORUM