apiVersion: v1
kind: Service
metadata:
  name: sunbird-yugabyte-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: sunbird-yugabyte
    component: yugabyte-ui
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 7000
    targetPort: 7000
  selector:
    app: sunbird-yugabyte
---
apiVersion: v1
kind: Service
metadata:
  name: sunbird-yugabyte-tserver
  namespace: {{ .Values.namespace }}
  labels:
    app: sunbird-yugabyte
    component: tserver
spec:
  clusterIP: None
  ports:
  - name: yql
    port: 9042
    targetPort: 9042
  - name: yql-http
    port: 12000
    targetPort: 12000
  - name: ysql
    port: 5433
    targetPort: 5433
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: sunbird-yugabyte
    component: tserver
---
apiVersion: v1
kind: Service
metadata:
  name: sunbird-yugabyte-master
  namespace: {{ .Values.namespace }}
  labels:
    app: sunbird-yugabyte
    component: master
spec:
  clusterIP: None
  ports:
  - name: master-ui
    port: 7000
    targetPort: 7000
  - name: master-rpc
    port: 7100
    targetPort: 7100
  selector:
    app: sunbird-yugabyte
    component: master
