package org.sunbird.graph.dac.enums;

public enum GraphDACErrorCodes {
    
    ERR_GRAPH_NULL_DB_NODE,
    
    ERR_GRAPH_NULL_DB_REL,

    ERR_CREATE_RELATION_MISSING_REQ_PARAMS,
    
    ERR_GET_NODE_MISSING_REQ_PARAMS,

    ERR_GET_NODE_LIST_MISSING_REQ_PARAMS,

    ERR_CHECK_LOOP_MISSING_REQ_PARAMS,
    
    ERR_GRAPH_TRAVERSAL,
    
    ERR_GRAPH_UPDATE_RELATION,
    
    ERR_GRAPH_DELETE_RELATION,
    
    ERR_GRAPH_GET_RELATION,
    
    ERR_GRAPH_ADD_RELATION,
    
    ERR_GRAPH_ADD_NODE,
    
    ERR_GRAPH_UPDATE_NODE,
    
    ERR_GRAPH_DELETE_NODE,
    
    ERR_GRAPH_IMPORT_NODE,
    
    ERR_GRAPH_GET_NODE,
    
    ERR_GRAPH_SEARCH_NODE,
    
    ERR_GRAPH_INVALID_RELATION;
}
